# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import parser_pb2 as parser__pb2


class ParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
            "/parser.Parser/Parse",
            request_serializer=parser__pb2.Request.SerializeToString,
            response_deserializer=parser__pb2.Response.FromString,
        )


class ParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Parse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Parse": grpc.unary_unary_rpc_method_handler(
            servicer.Parse,
            request_deserializer=parser__pb2.Request.FromString,
            response_serializer=parser__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "parser.Parser", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Parser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Parse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/parser.Parser/Parse",
            parser__pb2.Request.SerializeToString,
            parser__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
