# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parser.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cparser.proto\x12\x06parser"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x06Parser\x12,\n\x05Parse\x12\x0f.parser.Request\x1a\x10.parser.Response"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "parser_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_REQUEST"]._serialized_start = 24
    _globals["_REQUEST"]._serialized_end = 47
    _globals["_RESPONSE"]._serialized_start = 49
    _globals["_RESPONSE"]._serialized_end = 76
    _globals["_PARSER"]._serialized_start = 78
    _globals["_PARSER"]._serialized_end = 132
# @@protoc_insertion_point(module_scope)
